// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPXs3ioJXlNhxJz7yST0SPCpMnedjLTwQ',
    appId: '1:227812831469:web:30809fb3464d4342745ce4',
    messagingSenderId: '227812831469',
    projectId: 'u22-flutter',
    authDomain: 'u22-flutter.firebaseapp.com',
    storageBucket: 'u22-flutter.appspot.com',
    measurementId: 'G-P9MYKQ8QX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMMYQFp9ZVkounv6gwvl9hchZRpqFVvJ0',
    appId: '1:227812831469:android:b2f1d285add2575d745ce4',
    messagingSenderId: '227812831469',
    projectId: 'u22-flutter',
    storageBucket: 'u22-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFOwP7EYTpNosLxYhDvw0FYMiGDzNvh-Q',
    appId: '1:227812831469:ios:3323a47c0cdec078745ce4',
    messagingSenderId: '227812831469',
    projectId: 'u22-flutter',
    storageBucket: 'u22-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFOwP7EYTpNosLxYhDvw0FYMiGDzNvh-Q',
    appId: '1:227812831469:ios:3323a47c0cdec078745ce4',
    messagingSenderId: '227812831469',
    projectId: 'u22-flutter',
    storageBucket: 'u22-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
